# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13pZ4ppQ5glX1qYf9bE3gQWfbWszcgMz8
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModel
from datasets import load_dataset
import random
import requests
import os

# ==========================================
# 1. AUTHENTICATED DOWNLOAD
# ==========================================
LOCAL_PATH = "Hegelian_Bert.pth"
URL = f"https://huggingface.co/Saraquel/Hegelian_Bert/resolve/main/Hegelian_Bert.pth"

def download_weights():
    if os.path.exists(LOCAL_PATH):
        print(f"--- Weights confirmed locally at {LOCAL_PATH} ---")
        return

    print(f"--- Downloading weights from {URL} ---")

    hf_token = os.getenv("HF_TOKEN")
    if not hf_token:
        raise ValueError("Hugging Face token (HF_TOKEN) not found in environment variables. Please set it.")

    headers = {"Authorization": f"Bearer {hf_token}"}
    response = requests.get(URL, headers=headers, stream=True)

    if response.status_code == 200:
        with open(LOCAL_PATH, "wb") as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        print("--- Download Complete ---")
    else:
        response.raise_for_status()

download_weights()

# ==========================================
# 2. MATCHED ARCHITECTURE
# ==========================================
class DifferentialAttention(nn.Module):
    def __init__(self, h):
        super().__init__()
        self.scale = (h//8)**-0.5
        self.pos_q=nn.Linear(h,h); self.pos_k=nn.Linear(h,h); self.pos_v=nn.Linear(h,h)
        self.neg_q=nn.Linear(h,h); self.neg_k=nn.Linear(h,h)
        self.gate=nn.Linear(h*2,h); self.out=nn.Linear(h,h)
    def forward(self, x):
        p = torch.matmul(self.pos_q(x), self.pos_k(x).transpose(-2,-1))*self.scale
        p = F.softmax(p,-1)
        p = torch.matmul(p,self.pos_v(x))

        n = torch.matmul(self.neg_q(x), self.neg_k(x).transpose(-2,-1))*self.scale
        n = torch.sigmoid(n)
        n = torch.matmul(n,self.pos_v(x))

        g = torch.sigmoid(self.gate(torch.cat([p,n],-1)))
        return self.out(p*g - (n*(1-g)))

class HegelianBERT(nn.Module):
    def __init__(self):
        super().__init__()
        self.bert = AutoModel.from_pretrained("microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext")
        self.logic_layer = DifferentialAttention(768)
        self.norm = nn.LayerNorm(768)
        self.classifier = nn.Linear(768, 2)

    def forward(self, input_ids, mask):
        x = self.bert(input_ids, mask).last_hidden_state
        return self.classifier(self.norm(x + self.logic_layer(x)).mean(dim=1))

# ==========================================
# 3. HEGELIAN AUDIT DEMO
# ==========================================
def run_proposal_demo():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    tokenizer = AutoTokenizer.from_pretrained("microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext")

    model = HegelianBERT().to(device)
    model.load_state_dict(torch.load(LOCAL_PATH, map_location=device))
    model.eval()

    ds = load_dataset("shzyk/DiagnosisArena", split='test')
    case = random.choice(ds)

    print("\n" + "="*85)
    print(" FELLOWSHIP DEMO: CLINICAL SUBLATION & REASONING TRACE ")
    print("="*85)
    print(f"CASE EXCERPT: {case['Case Information'][:300]}...")
    print("-" * 85)
    print(f"{'DIAGNOSTIC HYPOTHESIS':<35} | {'THESIS (%)':<12} | {'NEGATION (%)':<12} | {'RESULT'}")
    print("-" * 85)

    for key, hypothesis in case['Options'].items():
        input_text = f"CASE: {case['Case Information']} [SEP] HYPOTHESIS: {hypothesis}"
        inputs = tokenizer(input_text, return_tensors="pt", padding=True, truncation=True, max_length=512).to(device)

        with torch.no_grad():
            logits = model(inputs.input_ids, inputs.attention_mask)
            probs = F.softmax(logits, dim=1)[0]

            thesis_score = probs[0].item() * 100      # Label 0: Viable
            antithesis_score = probs[1].item() * 100  # Label 1: Contradiction

        status = "SUBLATED" if thesis_score > antithesis_score else "REJECTED"
        is_correct = "*" if key == case['Right Option'] else " "

        print(f"{hypothesis[:35]:<35} | {thesis_score:>10.2f}% | {antithesis_score:>10.2f}% | {status} {is_correct}")

    print("-" * 85)
    print("PROPOSAL NOTE: The 'Negation' score quantifies clinical contradictions identified by")
    print("the Differential Attention layer, mirroring the Hegelian 'Antithesis'.")
    print("="*85)

if __name__ == "__main__":
    run_proposal_demo()

"""# HegelianBERT: Clinical Sublation & Reasoning Trace

This repository contains the implementation of **HegelianBERT**, a specialized BERT-based model designed for clinical diagnostic reasoning. It introduces a novel **Differential Attention** mechanism to identify both supporting evidence (thesis) and contradictions (negation) within clinical texts, enabling a more nuanced diagnostic outcome.

## Project Structure

- `Hegelian_Bert.py`: The main Python script containing the model definition, weight download function, and a demonstration of its clinical diagnostic reasoning capabilities.
- `Hegelian_Bert.pth`: (Downloaded automatically by the script) Pre-trained model weights for HegelianBERT.

## Features

- **HegelianBERT Model**: Extends `microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext` with custom layers.
- **Differential Attention**: A unique attention mechanism that computes both 'positive' (supportive) and 'negative' (contradictory) attention weights, inspired by Hegelian dialectics.
- **Clinical Diagnostic Demo**: Showcases the model's ability to analyze clinical cases and provide a 'reasoning trace' with 'Thesis' and 'Negation' scores for diagnostic hypotheses.

## Getting Started

### Prerequisites

Ensure you have Python 3.8+ installed. You will also need `pip` for dependency management.

### Installation

1.  **Clone the repository** (if this were a git repo):

    ```bash
    git clone https://github.com/your-username/HegelianBERT.git
    cd HegelianBERT
    ```

2.  **Install the required Python packages**:

    ```bash
    pip install torch transformers datasets requests
    ```

### Running the Demo

The `Hegelian_Bert.py` script will automatically download the necessary model weights and run a clinical diagnostic demo using a random case from the `shzyk/DiagnosisArena` dataset.

To run the demo:

```bash
python Hegelian_Bert.py
```

### Expected Output

The script will output a reasoning trace for a randomly selected clinical case, presenting diagnostic hypotheses with their 'Thesis (%)' (viability score) and 'Negation (%)' (contradiction score), and a final 'SUBLATED' or 'REJECTED' status. An asterisk `*` denotes the correct diagnosis.

```
=====================================================================================
 FELLOWSHIP DEMO: CLINICAL SUBLATION & REASONING TRACE
=====================================================================================
CASE EXCERPT: A 12-year-old female presented with bilateral vision loss for 2 weeks after 5-month application of repeated low-level red-light (RLRL) laser exposure for bilateral moderate myopia. One month before presentation, the patient complained of abnormally bright light and prolonged afterimages after exposu...
-------------------------------------------------------------------------------------
DIAGNOSTIC HYPOTHESIS               | THESIS (%)   | NEGATION (%) | RESULT
-------------------------------------------------------------------------------------
Toxic retinopathy due to red-light  |      58.82% |      41.18% | SUBLATED  
Bilateral foveal photoreceptor and  |      46.79% |      53.21% | REJECTED *
Photic retinopathy secondary to low |      55.00% |      45.00% | SUBLATED  
Solar retinopathy-like phototoxicit |      34.08% |      65.92% | REJECTED  
-------------------------------------------------------------------------------------
PROPOSAL NOTE: The 'Negation' score quantifies clinical contradictions identified by
the Differential Attention layer, mirroring the Hegelian 'Antithesis'.
=====================================================================================
```

## Model Architecture

### HegelianBERT

```python
class HegelianBERT(nn.Module):
    def __init__(self):
        super().__init__()
        self.bert = AutoModel.from_pretrained("microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext")
        self.logic_layer = DifferentialAttention(768)
        self.norm = nn.LayerNorm(768)
        self.classifier = nn.Linear(768, 2)

    def forward(self, input_ids, mask):
        x = self.bert(input_ids, mask).last_hidden_state
        return self.classifier(self.norm(x + self.logic_layer(x)).mean(dim=1))
```

### DifferentialAttention

```python
class DifferentialAttention(nn.Module):
    def __init__(self, h):
        super().__init__()
        self.scale = (h//8)**-0.5
        self.pos_q=nn.Linear(h,h); self.pos_k=nn.Linear(h,h); self.pos_v=nn.Linear(h,h)
        self.neg_q=nn.Linear(h,h); self.neg_k=nn.Linear(h,h)
        self.gate=nn.Linear(h*2,h); self.out=nn.Linear(h,h)
    def forward(self, x):
        p = torch.matmul(self.pos_q(x), self.pos_k(x).transpose(-2,-1))*self.scale
        p = F.softmax(p,-1)
        p = torch.matmul(p,self.pos_v(x))

        n = torch.matmul(self.neg_q(x), self.neg_k(x).transpose(-2,-1))*self.scale
        n = torch.sigmoid(n)
        n = torch.matmul(n,self.pos_v(x))

        g = torch.sigmoid(self.gate(torch.cat([p,n],-1)))
        return self.out(p*g - (n*(1-g)))
```

# HegelianBERT: Clinical Sublation & Reasoning Trace Demo

This notebook demonstrates **HegelianBERT**, a specialized BERT-based model designed for clinical diagnostic reasoning. It incorporates a novel **Differential Attention** mechanism to identify not only supporting evidence (thesis) but also contradictions (negation) within clinical texts, enabling a more nuanced and 'sublated' diagnostic outcome.

## 1. Model Overview

HegelianBERT extends `microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext` with a custom `DifferentialAttention` layer and a classifier.

*   **PubMedBERT**: Provides a strong foundation in biomedical language understanding.
*   **DifferentialAttention**: This unique layer processes input in a way that allows the model to simultaneously compute 'positive' (supportive) and 'negative' (contradictory) attention weights. This mirrors the Hegelian dialectic of thesis and antithesis.
*   **Classifier**: A linear layer that takes the processed representations and outputs probabilities for two classes: 'Viable' (Thesis) and 'Contradiction' (Antithesis).

## 2. Weights Download

The `download_weights()` function handles the retrieval of the pre-trained HegelianBERT weights from Hugging Face. These weights are essential for running the demo.

## 3. Clinical Sublation Demo (`run_proposal_demo()`)

The `run_proposal_demo()` function showcases HegelianBERT's capability in a clinical diagnostic scenario:

1.  **Model Loading**: It initializes the HegelianBERT model and loads the pre-trained weights.
2.  **Dataset**: It utilizes a random case from the `shzyk/DiagnosisArena` dataset, which contains clinical case information and multiple diagnostic hypotheses.
3.  **Reasoning Trace**: For each diagnostic hypothesis, the model processes the combined case information and hypothesis.
4.  **Output**: It presents the 'Thesis (%)' (likelihood of the hypothesis being viable) and 'Negation (%)' (likelihood of the hypothesis being contradictory), along with a 'SUBLATED' or 'REJECTED' status.
    *   **SUBLATED**: Implies the model found more supporting evidence (Thesis) than contradictions (Negation).
    *   **REJECTED**: Implies the model found more contradictions (Negation) than supporting evidence (Thesis).

### Output Interpretation

*   **DIAGNOSTIC HYPOTHESIS**: The proposed diagnosis.
*   **THESIS (%)**: The model's confidence that the hypothesis is viable, based on supporting evidence.
*   **NEGATION (%)**: The model's confidence that the hypothesis is contradictory, based on conflicting information.
*   **RESULT**: Indicates whether the hypothesis was 'SUBLATED' (more thesis) or 'REJECTED' (more negation).
*   `*`: Denotes the correct diagnosis for the given case.

## 4. How to Run

Simply run the existing code cell. It will automatically download the necessary weights, define the model architecture, and execute the `run_proposal_demo()` function, displaying a reasoning trace for a randomly selected clinical case.
"""